version: '3.1'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./game_project:/usr/src/game_project:delegated
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php

  # PHP Service
  php:
    build: .docker/php
    volumes:
      - ./game_project:/usr/src/game_project:delegated
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "3306:3306"

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  node:
    build: .docker/node
    container_name: angular_node
    ports:
      - 4200:4200
    volumes:
      - ${ANGULAR_APP}:/home/node/app/frontend
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        cd /home/node/app/frontend && npm-install && npm start
    expose:
      - "4200"

# Volumes
volumes:

  mysqldata: